# 👋 Akshat Jain

📍 Materials Science Engineering Student @ Arizona State University  
📫 ajain357@asu.edu | [LinkedIn](https://www.linkedin.com/in/akshatjain13)  
🔬 Researcher in 2D Materials | 🧪 CVD Systems | 🏭 Steel Manufacturing | 🎓 STEM Outreach

---

## 📚 About Me

Hi, I’m Akshat Jain — a passionate undergraduate at Arizona State University majoring in Materials Science and Engineering. I bring hands-on experience across research, education, and industrial manufacturing, with a focus on **2D materials synthesis**, **CVD engineering**, and **high-pressure material processing**. With roots in the steel manufacturing industry and an eye on the future of nanotechnology, I aim to bridge foundational metallurgy with cutting-edge materials science.

---

## 🔬 Research Experience

### 🧪 Tongay Research Group, ASU  
**Research Assistant** (Oct 2024 – Present)  
- Designed and built a **custom Reverse Flow CVD system** for 2D monolayer growth.
- Synthesized **WS₂ and WSe₂ films**, optimizing growth conditions to improve domain size and uniformity.
- Integrated literature review into experimental design, adjusting parameters based on real-time findings.

### 🧫 Eyring Materials Center, ASU  
**Research Lab Assistant** (Jul 2024 – Present)  
- Helped implement **4 new high-pressure apparatuses**; collaborated on multi-lab experiments.
- Worked with the **COMPRES team** to support >40 labs globally with multi-anvil press assemblies.
- Synthesized novel materials under high pressure; organized outreach events for public education.

---

## 👨‍🏫 Teaching & Leadership

### 📘 FSE-100, Ira A. Fulton Schools  
**Undergraduate Teaching Assistant** (Aug 2024 – Dec 2024)  
- Mentored first-year students through design projects, technical communication, and collaboration.

### 💼 Material Advantage Club  
**Treasurer** (Apr 2025 – Present)  
- Managed budgeting, reimbursements, and financial planning.
- Supported technical workshops and outreach events in coordination with ASU financial services.

---

## 🏭 Industrial Experience

### 🔧 Shree Shankeshwar Alloys LLP, India  
**Quality Manager Assistant** (Jun 2023 – Dec 2023)  
- Maintained and improved **steel quality control** processes.
- Operated stainless steel melting systems and analyzed production data from induction furnaces.

---

## 🧰 Skills & Tools

- **Chemical Vapor Deposition (CVD):** Reverse flow thin-film synthesis  
- **2D Materials Synthesis:** Monolayer TMD growth  
- **Characterization:** Raman/PL, XRD, Spectrophotometer  
- **High-Pressure Tools:** Multi-anvil press systems  
- **Metallurgy Tools:** Induction furnace operations, alloy formulation  

---

## 🌟 Extra-Curricular Activities

- FORCE @ ASU – Open House Volunteer (2024, 2025)  
- **eUReka 2.0:** Selected for the *Gauss Gun Project*, IAR Gandhinagar, India

---

## 📎 Useful Links

- [Tongay Research Group](https://faculty.engineering.asu.edu/tongay/)  
- [Materials Research Facilities – Eyring Center](https://cores.research.asu.edu/materials/about)  
- [Shankheshwar Alloys](https://shankheshwarsteels.com/)  
- [FORCE @ ASU](https://force.asu.edu/)  
